POST http://http://127.0.0.1:8000/login
Content-Type: application/json
{"username": "zack", "password": "Pass1234!"}


POST http://http://127.0.0.1:8000/signup
Content-Type: application/json
{"username": "zack", "password": "Pass1234!", "email": "zack@gmail.com"}



GET http://http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization:  Token 7492898fd70255cd681e7a9151ae3d2fc7a66eeb
{}

